# Generated by Django 3.1.1 on 2020-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, null=True),
        ),
    ]
