version: '3'

services:
  web:
    restart: always
    build: .
    command: python challenge/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - db
  migration:
    build: .
    command: python challenge/manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=topsecret123
      - MYSQL_DATABASE=paxful_db
      - MYSQL_USER=paxful_user
      - MYSQL_PASSWORD=paxful_password 