# Generated by Django 3.1.1 on 2020-09-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='profit',
        ),
    ]
